/* autogenerated by Processing revision 1283 on 2022-07-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import hype.*;
import hype.extended.behavior.HTween;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HTween_001 extends PApplet {




HRect  r1, r2, r3;

HTween t1a;
HTween t2a, t2b;
HTween t3a, t3b, t3c, t3d;

 public void setup() {
	/* size commented out by preprocessor */;
	H.init(this).background(0xFF242424).autoClear(false);

	// Rect 1 and tween

	r1 = new HRect(100).rounding(10);
	r1
		.stroke(0xFF000000, 100)
		.fill(0xFFFF9900)
		.anchorAt(H.CENTER)
		.loc(125,125)
		.rotation(45)
	;
	H.add(r1);

	t1a = new HTween()
		.target(r1).property(H.LOCATION)
		.start( r1.x(), r1.y() )
		.end( r1.x(), height - 125 )
		.ease(0.005f)
		.spring(0.95f)
	;

	// Rect 2 and tweens

	H.add(r2 = new HRect(100)).rounding(10).stroke(0xFF000000, 100).fill(0xFFFF6600).anchorAt(H.CENTER).loc(width/2,125).rotation(45);

	t2a = new HTween().target(r2).property(H.LOCATION).start( r2.x(), r2.y() ).end( r2.x(), height - 125 ).ease(0.005f).spring(0.95f);
	t2b = new HTween().target(r2).property(H.SCALE).start(0).end(1).ease(0.005f).spring(0.95f);

	// Rect 3 and tweens

	H.add(r3 = new HRect(100)).rounding(10).stroke(0xFF000000, 100).fill(0xFFFF3300).anchorAt(H.CENTER).loc(width-125,125).rotation(45);

	t3a = new HTween().target(r3).property(H.LOCATION).start( r3.x(), r3.y() ).end( r3.x(), height - 125 ).ease(0.005f).spring(0.95f);
	t3b = new HTween().target(r3).property(H.SCALE).start(0).end(1).ease(0.005f).spring(0.95f);
	t3c = new HTween().target(r3).property(H.ALPHA).start(0).end(255).ease(0.005f).spring(0.95f);
	t3d = new HTween().target(r3).property(H.ROTATION).start(-45).end(405).ease(0.005f).spring(0.95f);
}

 public void draw() {
	H.drawStage();
}


  public void settings() { size(640, 640); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HTween_001" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
