/* autogenerated by Processing revision 1283 on 2022-07-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import hype.*;
import hype.extended.behavior.HOrbiter3D;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HOrbiter3D_006 extends PApplet {




HOrbiter3D orb1, orb2;

 public void setup() {
	/* size commented out by preprocessor */;
	H.init(this).background(0xFF242424).use3D(true);

	HRect d = new HRect(50).rounding(4);
	d.noStroke().fill(0xFFFF3300).anchorAt(H.CENTER).rotation(45);
	H.add(d);

	orb1 = new HOrbiter3D(width/2, height/2, 0)
		.zSpeed(-1)
		.radius(200)
	;

	orb2 = new HOrbiter3D(width/2, height/2, 0)
		.target(d)
		.zSpeed(5)
		.radius(75)
		.parent(orb1)
	;
}

 public void draw() {
	H.drawStage();

	//simple sphere mesh to show orbit range
	pushMatrix();
		translate(width/2, height/2, 0);
		stroke(0xFF333333);
		noFill();
		sphereDetail(20);
		sphere(200);
	popMatrix();

	pushMatrix();
		translate(orb1.x(), orb1.y(), orb1.z());
		stroke(0xFF4D4D4D);
		noFill();
		sphereDetail(20);
		sphere(75);
	popMatrix();
}


  public void settings() { size(640, 640, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HOrbiter3D_006" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
