/* autogenerated by Processing revision 1283 on 2022-07-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import hype.*;
import hype.extended.behavior.HSwarm;
import hype.extended.behavior.HTimer;
import hype.extended.colorist.HColorPool;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HSwarm_002 extends PApplet {






HSwarm        swarm;
HDrawablePool pool;
HTimer        timer;

 public void setup() {
	/* size commented out by preprocessor */;
	H.init(this).background(0xFF242424);

	swarm = new HSwarm()
		.addGoal(width/2,height-200)
		.speed(4)
		.turnEase(0.025f)
		.twitch(0)
	;

	pool = new HDrawablePool(40);
	pool.autoAddToStage()
		.add(new HRect().rounding(4).size(18,6))
		.colorist(new HColorPool(0xFFFFFFFF, 0xFFF7F7F7, 0xFFECECEC, 0xFF333333, 0xFF0095A8, 0xFF00616F, 0xFFFF3300, 0xFFFF6600).fillOnly())
		.onCreate(
			new HCallback() {
				public void run(Object obj) {
					float r = random(TWO_PI);

					HDrawable d = (HDrawable) obj;
					d
						.noStroke()
						.loc(width/2, 200)
						.rotationRad(r)
						.move(cos(r)*10, sin(r)*10)
						.anchorAt(H.CENTER)
					;

					swarm.addTarget(d);
				}
			}
		)
	;

	timer = new HTimer()
		.numCycles( pool.numActive() )
		.interval(250)
		.callback(
			new HCallback() { 
				public void run(Object obj) {
					pool.request();
				}
			}
		)
	;
}

 public void draw() {
	H.drawStage();

	// draw an ellipse to show swarm point
	noFill(); strokeWeight(2); stroke(0xFF0095A8);
	ellipse(width/2, height-200, 4, 4);

	// draw an ellipse to show creation point
	noFill(); strokeWeight(2); stroke(0xFFFF3300);
	ellipse(width/2, 200, 4, 4);
}


  public void settings() { size(640, 640); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HSwarm_002" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
