/* autogenerated by Processing revision 1283 on 2022-07-12 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class day2 extends PApplet {

 public void setup() {
	/* size commented out by preprocessor */;
	background(0xFFFF3300);
}

 public void draw() {
	
}


  public void settings() { size(900, 900, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "day2" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
