/* autogenerated by Processing revision 1283 on 2022-07-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import hype.*;
import hype.extended.colorist.HPixelColorist;
import hype.extended.layout.HGridLayout;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HPixelColorist_001 extends PApplet {





HDrawablePool pool;
int           cellSize = 25;

 public void setup() {
	/* size commented out by preprocessor */;
	H.init(this).background(0xFF242424);

	final HPixelColorist colors = new HPixelColorist("sintra.jpg")
		.fillOnly()
		// .strokeOnly()
		// .fillAndStroke()
	;

	pool = new HDrawablePool(576);
	pool.autoAddToStage()
		.add (new HRect().rounding(4))
		.layout(new HGridLayout().startX(21).startY(21).spacing(cellSize+1,cellSize+1).cols(24))
		.onCreate (
			new HCallback(){
				public void run(Object obj) {
					HDrawable d = (HDrawable) obj;
					d.noStroke().anchorAt(H.CENTER).size(cellSize);

					colors.applyColor(d);
				}
			}
		)
		.requestAll()
	;

	H.drawStage();
	noLoop();
}

 public void draw() {

}


  public void settings() { size(640, 640); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HPixelColorist_001" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
