/* autogenerated by Processing revision 1283 on 2022-07-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import hype.*;
import hype.extended.behavior.HParticles;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HParticles_001 extends PApplet {




HDrawablePool pool;
HParticles    hp;

 public void setup() {
	/* size commented out by preprocessor */; 
	H.init(this).background(0xFF242424).use3D(true);

	hp = new HParticles()
		.location(width/2, height/2)
		.minimumLife(10)
		.maximumLife(150)
		.speed(3.0f)
		.decay(1.0f)
		.fade(false)
	;

	pool = new HDrawablePool(400);
	pool.autoAddToStage()
		.add(new HSprite())
		.onCreate(
			new HCallback() {
				public void run(Object obj) {
					HDrawable d = (HDrawable) obj;
					d.noStroke().fill(255).size(5).anchorAt(H.CENTER).rotation(45);
					hp.addParticle(d);
				}
			}
		)
		.requestAll()
	;
}


 public void draw() {
	H.drawStage();
}


  public void settings() { size(640, 640, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HParticles_001" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
