/* autogenerated by Processing revision 1283 on 2022-07-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.Iterator;
import hype.*;
import hype.extended.behavior.HSwarm;
import hype.extended.behavior.HTimer;
import hype.extended.behavior.HTween;
import hype.extended.colorist.HColorPool;
import hype.interfaces.HLocatable;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HSwarm_007 extends PApplet {










HColorPool    colors;
HCanvas       canvas;
HSwarm        swarm;
HDrawablePool pool;
HTimer        timer;
int           i=0;

 public void setup() {
	/* size commented out by preprocessor */;
	H.init(this).background(0xFF242424);

	colors = new HColorPool(0xFFFFFFFF, 0xFFF7F7F7, 0xFFECECEC, 0xFF333333, 0xFF0095A8, 0xFF00616F, 0xFFFF3300, 0xFFFF6600);

	H.add(canvas = new HCanvas()).autoClear(false).fade(40);

	swarm = new HSwarm()
		.speed(4)
		.turnEase(0.1f)
		.twitch(15)
		.idleGoal(width/2,height/2)
	;

	pool = new HDrawablePool(10);
	pool.autoAddToStage()
		.add(new HRect(10).rounding(5))
		.onCreate(
			new HCallback() {
				public void run(Object obj) {
					final HDrawable d = (HDrawable) obj;
					d
						.strokeWeight(2)
						.stroke(0xFFECECEC)
						.fill(0xFF111111)
						.loc((int)random(100,540), (int)random(100,540))
						.anchorAt(H.CENTER)
						.rotation(45)
					;

					final HTween tween = new HTween()
						.target(d).property(H.LOCATION)
						.start(d.x(), d.y())
						.end((int)random(width), (int)random(height))
						.ease(0.01f).spring(0.9f)
					;

					final HCallback onAnim = new HCallback() {
						public void run(Object obj) {
							tween
								.start(d.x(), d.y())
								.end((int)random(100,540), (int)random(100,540))
								.ease(0.01f)
								.spring(0.9f)
								.register()
							;
						}
					};

					timer = new HTimer().interval(2000).callback(onAnim);
				}
			}
		)
		.requestAll()
	;
}

 public void draw() {
	if(i++<100) { 
		swarm.addTarget(
			canvas.add(
				new HRect(8,2)
				.rounding(4)
				.anchorAt( H.CENTER )
				.noStroke()
				.fill(colors.getColor())
			)
		);
	}

	H.drawStage();

	for(Iterator<HLocatable> it=swarm.goals().iterator();it.hasNext();) {
		it.remove();
		it.next();
	}

	for(HDrawable d : pool) {
		swarm.addGoal(d.x(),d.y());
	}
}


  public void settings() { size(640, 640); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HSwarm_007" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
